sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alex/new_test -f Dockerfile.dev . 

script:
  - docker run -e CI=true alex/new_test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-us-east-1-145699711769"
  bucket_path: "test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"