sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alex/new_test -f Dockerfile.dev . 

script:
  - docker run -e CI=true alex/new_test npm run test -- --coverage